; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
extra_scripts = pre:read_env.py

build_flags =
    -D MQTT_MAX_PACKET_SIZE=2048
    -D MQTT_MAX_TRANSFER_SIZE=2048

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    adafruit/Adafruit BusIO @ ^1.14.5
    adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.3
    olikraus/U8g2_for_Adafruit_GFX @ ^1.8.0
    bblanchon/ArduinoJson @ ^6.21.5
    knolleary/PubSubClient @ ^2.8
    miguelbalboa/MFRC522 @ ^1.4.11
